const menu = [
    {
      id: 1,
      title: 'Beef',
      category: 'breakfast',
      price: 1500,
      img: './2.png',
      desc: `mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'Chicken Fries',
      category: 'lunch',
      price: 2000,
      img: './3.png',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'White yam with Sauce',
      category: 'shakes',
      price: 1200,
      img: './4.png',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'Fried Rice',
      category: 'breakfast',
      price: 900,
      img: './5.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'Toast Bread',
      category: 'lunch',
      price: 900,
      img: './6.png',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Green Tea',
      category: 'shakes',
      price: 300,
      img: './7.png',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'Pancake',
      category: 'breakfast',
      price: 500,
      img: './8.png',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Beans',
      category: 'lunch',
      price: 700,
      img: './9.png',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Jollof Rice',
      category: 'shakes',
      price: 1000,
      img: './10.png',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;